# Generated by Django 5.2.8 on 2025-11-13 18:11

import autoslug.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=256)),
                ('author_link', models.URLField()),
            ],
            options={
                'ordering': ['author_name'],
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_code', models.CharField(max_length=256, unique=True)),
                ('book_name', models.CharField(max_length=256)),
                ('book_link', models.URLField()),
                ('book_author', models.ManyToManyField(related_name='books', to='mainapp.author')),
            ],
            options={
                'ordering': ['book_name'],
            },
        ),
        migrations.CreateModel(
            name='IssueBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999)])),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('is_returned', models.BooleanField(default=False)),
                ('issue_id', autoslug.fields.AutoSlugField(editable=False, populate_from='book', unique=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.books')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='OverDueBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('over_due_id', autoslug.fields.AutoSlugField(editable=False, populate_from='issue__issue_id', unique=True)),
                ('issue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.issuebook')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_name', models.CharField(max_length=256)),
                ('publication_link', models.URLField()),
                ('author', models.ManyToManyField(related_name='publications', to='mainapp.author')),
            ],
            options={
                'ordering': ['publication_name'],
            },
        ),
        migrations.AddField(
            model_name='books',
            name='book_publication',
            field=models.ManyToManyField(related_name='books', to='mainapp.publication'),
        ),
    ]
