# Generated by Django 5.2.8 on 2025-11-29 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=256)),
                ('author_link', models.CharField(max_length=1024, unique=True)),
            ],
            options={
                'ordering': ['author_name'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_name', models.CharField(max_length=256, unique=True)),
                ('publication_link', models.CharField(max_length=1024)),
            ],
            options={
                'ordering': ['publication_name'],
            },
        ),
        migrations.CreateModel(
            name='Specimens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specimen_code', models.CharField(max_length=256, unique=True)),
                ('specimen_name', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ['specimen_name'],
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_code', models.CharField(max_length=256, unique=True)),
                ('book_name', models.CharField(max_length=256)),
                ('book_link', models.CharField(max_length=1024)),
                ('book_author', models.ManyToManyField(related_name='books', to='mainapp.author')),
                ('book_publication', models.ManyToManyField(related_name='books', to='mainapp.publication')),
            ],
            options={
                'ordering': ['book_name'],
            },
        ),
        migrations.CreateModel(
            name='IssueBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.IntegerField(default=0)),
                ('student_name', models.CharField(default='', max_length=64)),
                ('student_grade', models.IntegerField(default=0)),
                ('student_section', models.CharField(default='', max_length=1)),
                ('returned', models.BooleanField(default=False)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.books', unique=True)),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Magazines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magazine_code', models.CharField(max_length=256, unique=True)),
                ('magazine_name', models.CharField(max_length=256)),
                ('magazine_link', models.CharField(max_length=1024)),
                ('magazine_author', models.ManyToManyField(related_name='magazines', to='mainapp.author')),
                ('magazine_publication', models.ManyToManyField(related_name='magazines', to='mainapp.publication')),
            ],
            options={
                'ordering': ['magazine_name'],
            },
        ),
        migrations.CreateModel(
            name='IssueMagazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.IntegerField(default=0)),
                ('student_name', models.CharField(default='', max_length=64)),
                ('student_grade', models.IntegerField(default=0)),
                ('student_section', models.CharField(default='', max_length=1)),
                ('returned', models.BooleanField(default=False)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('magazine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.magazines')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='OverDueBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(default='', max_length=64)),
                ('student_grade', models.IntegerField(default=0)),
                ('admission_no', models.IntegerField(default=0)),
                ('date_issued', models.DateField(null=True)),
                ('date_supposed_to_be_returned', models.DateField(null=True)),
                ('student_section', models.CharField(default='', max_length=1)),
                ('issue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.issuebook')),
            ],
            options={
                'ordering': ['-issue'],
            },
        ),
        migrations.CreateModel(
            name='OverDueMagazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(default='', max_length=64)),
                ('student_grade', models.IntegerField(default=0)),
                ('admission_no', models.IntegerField(default=0)),
                ('date_issued', models.DateField(null=True)),
                ('date_supposed_to_be_returned', models.DateField(null=True)),
                ('student_section', models.CharField(default='', max_length=1)),
                ('issue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.issuemagazine')),
            ],
            options={
                'ordering': ['-issue'],
            },
        ),
    ]
