# Generated by Django 5.2.8 on 2025-11-22 18:45

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='overduebook',
            options={'ordering': ['-issue']},
        ),
        migrations.RenameField(
            model_name='issuebook',
            old_name='is_returned',
            new_name='returned',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='author',
        ),
        migrations.AddField(
            model_name='issuebook',
            name='student_grade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='issuebook',
            name='student_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='issuebook',
            name='student_section',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='overduebook',
            name='admission_no',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='overduebook',
            name='fine_due',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overduebook',
            name='over_due_addition_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overduebook',
            name='student_grade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='overduebook',
            name='student_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='overduebook',
            name='student_section',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_link',
            field=models.CharField(max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_link',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='issuebook',
            name='admission_no',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='issuebook',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='overduebook',
            name='over_due_id',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='issue', unique=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_link',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
