# Generated by Django 6.0.4 on 2026-04-20 17:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'csv'])])),
            ],
        ),
        migrations.AlterField(
            model_name='issuemagazine',
            name='magazine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.magazines', unique=True),
        ),
    ]
