# Generated by Django 5.2.8 on 2025-11-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_publication_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_link',
            field=models.CharField(max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_link',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_link',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
