# Generated by Django 5.2.8 on 2025-11-22 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_overduebook_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overduebook',
            name='over_due_addition_day',
        ),
    ]
