# Generated by Django 6.0.4 on 2026-04-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_excelfileupload_alter_issuemagazine_magazine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='author_link',
        ),
        migrations.RemoveField(
            model_name='books',
            name='book_link',
        ),
        migrations.RemoveField(
            model_name='magazines',
            name='magazine_link',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='publication_link',
        ),
        migrations.AlterField(
            model_name='books',
            name='book_author',
            field=models.ManyToManyField(related_name='BOOKS', to='mainapp.author'),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_publication',
            field=models.ManyToManyField(related_name='BOOKS', to='mainapp.publication'),
        ),
        migrations.AlterField(
            model_name='magazines',
            name='magazine_author',
            field=models.ManyToManyField(related_name='books', to='mainapp.author'),
        ),
        migrations.AlterField(
            model_name='magazines',
            name='magazine_publication',
            field=models.ManyToManyField(related_name='books', to='mainapp.publication'),
        ),
    ]
