# Generated by Django 6.0.4 on 2026-04-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_author_author_link_remove_books_book_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_cost',
            field=models.CharField(default='0', max_length=256),
        ),
        migrations.AddField(
            model_name='books',
            name='book_pages',
            field=models.CharField(default='0', max_length=256),
        ),
        migrations.AddField(
            model_name='magazines',
            name='magazine_cost',
            field=models.CharField(default='0', max_length=256),
        ),
        migrations.AddField(
            model_name='magazines',
            name='magazine_pages',
            field=models.CharField(default='0', max_length=256),
        ),
    ]
