# Generated by Django 5.2.8 on 2025-11-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_author_author_link_alter_books_book_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuebook',
            name='issue_date',
            field=models.DateField(blank=True),
        ),
    ]
