# Generated by Django 5.2.8 on 2025-11-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_overduebook_over_due_addition_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overduebook',
            name='fine_due',
        ),
        migrations.AlterField(
            model_name='issuebook',
            name='admission_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='overduebook',
            name='admission_no',
            field=models.IntegerField(default=0),
        ),
    ]
