# Generated by Django 5.2.8 on 2025-11-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_overduebook_fine_due_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overduebook',
            name='date_issued',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='overduebook',
            name='date_supposed_to_be_returned',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='overduebook',
            name='id_of_issue',
            field=models.TextField(null=True),
        ),
    ]
