# Generated by Django 5.2.8 on 2025-11-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_issuebook_issue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebook',
            name='student_class',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='issuebook',
            name='student_name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
