# Generated by Django 6.0.4 on 2026-04-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_books_book_cost_books_book_pages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_bill_number',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='books',
            name='book_edition_description',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='books',
            name='book_isbn_no',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='books',
            name='book_language',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='books',
            name='book_place_of_publication',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='books',
            name='book_purchase_date',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='books',
            name='book_purchase_ref_name',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='magazines',
            name='magazine_bill_number',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='magazines',
            name='magazine_edition_description',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='magazines',
            name='magazine_isbn_no',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='magazines',
            name='magazine_language',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='magazines',
            name='magazine_place_of_publication',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='magazines',
            name='magazine_purchase_date',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='magazines',
            name='magazine_purchase_ref_name',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.RemoveField(
            model_name='books',
            name='book_author',
        ),
        migrations.AlterField(
            model_name='books',
            name='book_cost',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_pages',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.RemoveField(
            model_name='books',
            name='book_publication',
        ),
        migrations.RemoveField(
            model_name='magazines',
            name='magazine_author',
        ),
        migrations.RemoveField(
            model_name='magazines',
            name='magazine_publication',
        ),
        migrations.AddField(
            model_name='books',
            name='book_author',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='books',
            name='book_publication',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='magazines',
            name='magazine_author',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='magazines',
            name='magazine_publication',
            field=models.CharField(default='N/A', max_length=256),
        ),
    ]
