# Generated by Django 5.2.8 on 2025-11-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_issuebook_student_class_issuebook_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuebook',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
