# Generated by Django 5.2.8 on 2025-11-26 16:20

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_overduebook_date_issued_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specimens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specimen_code', models.CharField(max_length=256, unique=True)),
                ('specimen_name', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ['specimen_name'],
            },
        ),
        migrations.CreateModel(
            name='IssueMagazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.IntegerField(default=0)),
                ('student_name', models.CharField(default='', max_length=64)),
                ('student_grade', models.IntegerField(default=0)),
                ('student_section', models.CharField(default='', max_length=1)),
                ('returned', models.BooleanField(default=False)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('issue_id', autoslug.fields.AutoSlugField(editable=False, populate_from='magazine', unique=True)),
                ('magazine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.books')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Magazines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magazine_code', models.CharField(max_length=256, unique=True)),
                ('magazine_name', models.CharField(max_length=256)),
                ('magazine_link', models.CharField(max_length=1024)),
                ('magazine_author', models.ManyToManyField(related_name='magazines', to='mainapp.author')),
                ('magazine_publication', models.ManyToManyField(related_name='magazines', to='mainapp.publication')),
            ],
            options={
                'ordering': ['magazine_name'],
            },
        ),
        migrations.CreateModel(
            name='OverDueMagazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('over_due_id', autoslug.fields.AutoSlugField(editable=False, populate_from='issue', unique=True)),
                ('student_name', models.CharField(default='', max_length=64)),
                ('student_grade', models.IntegerField(default=0)),
                ('admission_no', models.IntegerField(default=0)),
                ('date_issued', models.DateField(null=True)),
                ('date_supposed_to_be_returned', models.DateField(null=True)),
                ('id_of_issue', models.TextField(null=True)),
                ('student_section', models.CharField(default='', max_length=1)),
                ('issue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.issuemagazine')),
            ],
            options={
                'ordering': ['-issue'],
            },
        ),
    ]
