# Generated by Django 5.2.8 on 2025-11-26 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_specimens_issuemagazine_magazines_overduemagazine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuebook',
            name='issue_id',
        ),
        migrations.RemoveField(
            model_name='issuemagazine',
            name='issue_id',
        ),
        migrations.RemoveField(
            model_name='overduebook',
            name='id_of_issue',
        ),
        migrations.RemoveField(
            model_name='overduebook',
            name='over_due_id',
        ),
        migrations.RemoveField(
            model_name='overduemagazine',
            name='id_of_issue',
        ),
        migrations.RemoveField(
            model_name='overduemagazine',
            name='over_due_id',
        ),
        migrations.AlterField(
            model_name='issuemagazine',
            name='magazine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.magazines'),
        ),
    ]
