# Generated by Django 5.2.8 on 2025-11-21 17:01

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_issuebook_issue_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='overduebook',
            options={'ordering': ['-issue']},
        ),
        migrations.AddField(
            model_name='overduebook',
            name='fine_due',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overduebook',
            name='over_due_addition_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='overduebook',
            name='over_due_id',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='issue', unique=True),
        ),
    ]
