# Generated by Django 5.2.8 on 2025-11-21 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_overduebook_options_overduebook_fine_due_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuebook',
            name='is_returned',
        ),
    ]
