# Generated by Django 5.2.8 on 2025-11-21 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_remove_issuebook_is_returned'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuebook',
            name='admission_no',
        ),
        migrations.RemoveField(
            model_name='issuebook',
            name='student_class',
        ),
        migrations.RemoveField(
            model_name='issuebook',
            name='student_name',
        ),
        migrations.AddField(
            model_name='issuebook',
            name='returned',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.IntegerField()),
                ('student_name', models.CharField(max_length=64)),
                ('student_mother_name', models.CharField(max_length=64)),
                ('student_father_name', models.CharField(max_length=64)),
                ('student_image', models.ImageField(upload_to='')),
                ('student_father_image', models.ImageField(upload_to='')),
                ('student_mother_image', models.ImageField(upload_to='')),
                ('student_address', models.TextField(blank=True, null=True)),
                ('student_grade', models.IntegerField()),
                ('student_section', models.CharField(max_length=1)),
                ('student_phone_number_father', models.IntegerField()),
                ('student_phone_number_mother', models.IntegerField()),
                ('student_mode_of_transfer', models.CharField(max_length=8)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='issuebook',
            name='issue_holder',
            field=models.ManyToManyField(related_name='issuebook', to='mainapp.students'),
        ),
    ]
