# Generated by Django 5.2.8 on 2025-11-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_remove_issuebook_admission_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overduebook',
            name='overdue_issue_holder',
            field=models.ManyToManyField(related_name='overdueissueholder', to='mainapp.students'),
        ),
    ]
